ktor {
    deployment {
        port = 20870
        port = ${?PORT}
    }
    application {
        modules = [ dev.tracedown.realtime.ApplicationKt.module ]
    }
}

database {
    url = ${DATABASE_URL}
    user = ${DATABASE_USER}
    password = ${DATABASE_PASSWORD}
}

redis {
    a {
        url = ${REDIS_A_URL}
    }
}

realtime {
    pingIntervalMs = 5000
    pingTimeoutMs = 10000
}
